kind: Service
apiVersion: v1
metadata:
  name: server
  labels:
    app: server
spec:
  selector:
    app: server
  ports:
    - name: grpc
      port: 999
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
      version: v1
  replicas: 3
  template:
    metadata:
      labels:
        app: server
        version: v1
    spec:
      restartPolicy: Always
      containers:
        - name: server
          image: registry.cn-qingdao.aliyuncs.com/istio-example/grpc-server:v1
          ports:
            - containerPort: 999
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 100Mi