kind: Service
apiVersion: v1
metadata:
  name: grpc-server
  labels:
    app: grpc-server
spec:
  selector:
    app: grpc-server
  ports:
    - name: http
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server-v1
spec:
  selector:
    matchLabels:
      app: grpc-server
      version: v1
  replicas: 3
  template:
    metadata:
      labels:
        app: grpc-server
        version: v1
    spec:
      restartPolicy: Always
      containers:
        - name: grpc-server
          image: registry.cn-qingdao.aliyuncs.com/istio-example/grpc-server:v1
          ports:
            - containerPort: 999
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 100Mi